parameters:
  environment: 'Dev'
  vmImage: ''
  resourceGroupName: ''
  logicAppName: ''
  folderName: ''
  logicAppProject: ''
  azureResourceManagerConnection: ''  
  subscriptionId: ''
  location: 'UK South'
  testscenarios: ['','']  
  triggerName: ''
  isAPIM: true
  namedParameters: ''
  logicAppParameters: ''
  keyVaultName: ''
  getAPIEndpoint: true
  getSecretsFromKeyVault: false
  templateFileName: ''
  paramFileName: ''
  logicApps:    
    - ['','','','']
  
    

jobs: 
  - deployment: Deploy_LogicApp  
    displayName: "Deploy ${{parameters.environment}} job"
    pool:
      vmImage: ${{parameters.vmImage}}
    environment : ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:               

                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: 'current'
                    path: '$(Pipeline.Workspace)'                 

                - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-logicApp-testscenarios-templatev2.yml                  
                  parameters:
                      environment: ${{parameters.environment}}
                      vmImage: 'vs2017-win2016'
                      resourceGroupName: ${{parameters.resourceGroupName}}
                      logicAppName: ${{parameters.logicAppName}}
                      logicAppProject: ${{parameters.logicAppProject}}
                      folderName: ${{parameters.folderName}}
                      azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                      subscriptionId: ${{parameters.subscriptionId}}
                      location: ${{parameters.location}}
                      testscenarios: ${{parameters.testscenarios}} 
                      triggerName: ${{parameters.triggerName}}
                      isAPIM: ${{parameters.isAPIM}}   
                      getAPIEndpoint: ${{parameters.getAPIEndpoint}}
                      namedParameters: ${{parameters.namedParameters}}
                      logicAppParameters: ${{parameters.logicAppParameters}}
                      getSecretsFromKeyVault: ${{parameters.getSecretsFromKeyVault}}
                      keyVaultName: ${{parameters.keyVaultName}}
                      logicApps: ${{parameters.logicApps}}

                - task: AzureResourceManagerTemplateDeployment@3
                  condition: ne('${{parameters.environment}}','Dev')
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}
                    subscriptionId: ${{parameters.subscriptionId}}
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: ${{parameters.resourceGroupName}}
                    location: ${{parameters.location}}
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/logicapp/${{parameters.templateFileName}}'
                    csmParametersFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/logicapp/${{parameters.paramFileName}}'                                        
                    overrideParameters: ${{parameters.logicAppParameters}}
                    deploymentMode: 'Incremental' 

