parameters:
  environment: 'Dev'
  vmImage: ''
  resourceGroupName: ''
  logicAppName: ''
  folderName: ''
  logicAppProject: ''
  azureResourceManagerConnection: ''  
  subscriptionId: ''
  location: 'UK South'
  testscenarios: ['','']  
  triggerName: ''
  isAPIM: true
  namedParameters: ''
  logicAppParameters: ''
  keyVaultName: ''
  getAPIEndpoint: true
  getSecretsFromKeyVault: false
  logicApps:    
    - ['','','','']
  testProjectname: ''
  integrationAccountName: ''
  integrationAccountResourceGroupName: ''
  publishMap: false
  maps:    
    - ['','','']
  deployServiceBus: false
  serviceBusparameters: ''
  deployServiceBusConnection: false
  serviceBusparametersConnection: ''
    

jobs: 
  - deployment: Deploy_LogicApp  
    displayName: "Deploy ${{parameters.environment}} job"
    pool:
      vmImage: ${{parameters.vmImage}}
    environment : ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:               

                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: 'current'
                    path: '$(Pipeline.Workspace)'                 
                    
                - checkout: git://KantarIntegrationPlatform/KH.Coupa@KH.Integ.PipelineTemplates 
                  path: ScriptsAndTemplates

                - ${{ if eq(parameters.publishMap, true) }}:
                  - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-integrationaccount-maps-template_1.yml 
                  
                    parameters:
                        publishMap: ${{parameters.publishMap}}
                        environment: ${{parameters.environment}}
                        vmImage: 'vs2017-win2016'
                        resourceGroupName: ${{parameters.integrationAccountResourceGroupName}}                        
                        logicAppProject: ${{parameters.logicAppProject}}
                        folderName: ${{parameters.folderName}}
                        azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                        subscriptionId: ${{parameters.subscriptionId}}
                        location: ${{parameters.location}}
                        integrationAccountName: ${{parameters.integrationAccountName}}
                        maps: ${{parameters.maps}}

                - ${{ if eq(parameters.deployServiceBus, true) }}:
                  - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-servicebus.yml 
                  
                    parameters:
                        environment: ${{parameters.environment}}
                        vmImage: 'windows-latest'
                        resourceGroupName: ${{parameters.resourceGroupName}}                        
                        projectName: ${{parameters.logicAppProject}}
                        azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                        subscriptionId: ${{parameters.subscriptionId}}
                        location: ${{parameters.location}}
                        namedParameters: ${{parameters.serviceBusparameters}}

                - ${{ if eq(parameters.deployServiceBusConnection, true) }}:
                  - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-servicebus-connection-template.yml 
                  
                    parameters:
                        environment: ${{parameters.environment}}
                        vmImage: 'windows-latest'
                        resourceGroupName: ${{parameters.resourceGroupName}}                        
                        projectName: ${{parameters.logicAppProject}}
                        azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                        subscriptionId: ${{parameters.subscriptionId}}
                        location: ${{parameters.location}}
                        namedParameters: ${{parameters.serviceBusparameters}}


                - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-logicApp-testscenarios-template.yml                  
                  parameters:
                      environment: ${{parameters.environment}}
                      vmImage: 'vs2017-win2016'
                      resourceGroupName: ${{parameters.resourceGroupName}}
                      logicAppName: ${{parameters.logicAppName}}
                      logicAppProject: ${{parameters.logicAppProject}}
                      folderName: ${{parameters.folderName}}
                      azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                      subscriptionId: ${{parameters.subscriptionId}}
                      location: ${{parameters.location}}
                      testscenarios: ${{parameters.testscenarios}} 
                      triggerName: ${{parameters.triggerName}}
                      isAPIM: ${{parameters.isAPIM}}   
                      getAPIEndpoint: ${{parameters.getAPIEndpoint}}
                      namedParameters: ${{parameters.namedParameters}}
                      logicAppParameters: ${{parameters.logicAppParameters}}
                      getSecretsFromKeyVault: ${{parameters.getSecretsFromKeyVault}}
                      keyVaultName: ${{parameters.keyVaultName}}
                      logicApps: ${{parameters.logicApps}}
                      testProjectname: ${{parameters.testProjectname}}

                - task: AzureResourceManagerTemplateDeployment@3
                  condition: ne('${{parameters.environment}}','Dev')
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}
                    subscriptionId: ${{parameters.subscriptionId}}
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: ${{parameters.resourceGroupName}}
                    location: ${{parameters.location}}
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/Logicapp/LogicApp.json'
                    csmParametersFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/logicapp/LogicApp.parameters.${{parameters.environment}}.json'                                        
                    overrideParameters: ${{parameters.logicAppParameters}}
                    deploymentMode: 'Incremental' 

                - ${{ if ne(parameters.environment, 'Dev') }}:
                  - template:  ${{variables['Build.StagingDirectory']}}/templates/azure-pipeline-deployment-APIM-template.yml                  
                    parameters:
                        environment: ${{parameters.environment}}
                        vmImage: 'vs2017-win2016'
                        resourceGroupName: ${{parameters.resourceGroupName}}
                        logicAppName: ${{parameters.logicAppName}}
                        logicAppProject: ${{parameters.logicAppProject}}
                        folderName: ${{parameters.folderName}}
                        azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}  
                        subscriptionId: ${{parameters.subscriptionId}}
                        location: ${{parameters.location}} 
                        triggerName: ${{parameters.triggerName}} 
                        isAPIM: ${{parameters.isAPIM}}   
                        getAPIEndpoint: ${{parameters.getAPIEndpoint}}
                        namedParameters: ${{parameters.namedParameters}}
                        getSecretsFromKeyVault: ${{parameters.getSecretsFromKeyVault}}
                        keyVaultName: ${{parameters.keyVaultName}}    
                        logicApps: ${{parameters.logicApps}}
                                 