parameters: 
  environment: 'Dev'
  vmImage: ''
  resourceGroupName: ''
  logicAppName: ''
  folderName: ''
  logicAppProject: ''
  azureResourceManagerConnection: ''  
  subscriptionId: ''
  location: 'UK South' 
  triggerName: ''
  isAPIM: true
  namedParameters: ''
  getAPIEndpoint: true
  keyVaultName: ''
  getSecretsFromKeyVault: false
  templateFileName: ''
  paramFileName: ''
  logicApps:    
    - ['','','','']
  

jobs: 
  - deployment: Deploy_API  
    displayName: "Deploy ${{parameters.environment}} job"
    pool:
      vmImage: ${{parameters.vmImage}}
    environment : ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:               

                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: 'current'
                    path: '$(Pipeline.Workspace)'                 
    
                - task: AzureResourceManagerTemplateDeployment@3
                  condition: ne('${{parameters.environment}}','Dev')
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: ${{parameters.azureResourceManagerConnection}}
                    subscriptionId: ${{parameters.subscriptionId}}
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: ${{parameters.resourceGroupName}}
                    location: ${{parameters.location}}
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/${{parameters.templateFileName}}'
                    csmParametersFile: '$(Pipeline.Workspace)/drop/${{parameters.logicAppProject}}/${{parameters.folderName}}/${{parameters.paramFileName}}'
        #         overrideParameters: -backendServiceUrl "$(baseUrl)" -backendTemplate "$(pathUrl)"


    
          